# configs/yolov11_gtsdb.yaml
task: detect
mode: train
model: yolo11n.pt
pretrained: true
data: configs/datav8_gtsdb.yaml
epochs: 300
patience: 10
imgsz: 1280
batch: 16
seed: 42,
lr0: 0.001
lrf: 0.01
rect: true
mosaic: 0.5
mixup: 0.05
cache: ram
workers: 4
single_cls: true
