# configs/yolov11_gtsdb.yaml
task: detect
mode: train
model: C:\Develop\Python\PyCharmProjects\iu_computer_vision\training\runs\gtsdb\v11\windows\v11_windows\weights\best.pt
pretrained: true
data: configs/datav8_fussgaenger.yaml
epochs: 300
patience: 30
imgsz: 1280
batch: 16
seed: 42
lr0: 0.001
lrf: 0.01
rect: true
mosaic: 0.5
mixup: 0.05
cache: ram
workers: 4
single_cls: true
