# training/configs/yolov11_colab.yaml
task: classify
mode: train
model: yolo11n-cls.pt
data: /content/yolo_cls
epochs: 150
patience: 10            # Early Stopping
imgsz: 512
batch: 16
seed: 42
project: runs/v11
name: exp
