# training/configs/yolov11_colab.yaml
task: classify
mode: train
model: yolo11n-cls.pt
data: configs/datav8_colab.yaml
epochs: 150
patience: 5            # Early Stopping
imgsz: 512
batch: 16
seed: 42
project: runs/v11
name: exp
